
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-06-20T13:42:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e249eb6c3facd6351e1f8d0da6f11630cdda8e2e",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
